towards nimskull in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,7 @@ jobs:
       # for them.
       - if: github.event_name != 'pull_request'
         name: Checkout (if not PR)
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - uses: dorny/paths-filter@v2
         id: filter
@@ -55,8 +55,13 @@ jobs:
       fail-fast: false
       matrix:
         os: [ubuntu-latest]
-        nim: [devel]
-    name: '${{ matrix.os }} (${{ matrix.nim }})'
+        compiler:
+          - name: nim
+            version: devel
+          - name: nimskull
+            version: "*"
+            docs: true
+    name: "${{ matrix.os }} (${{ matrix.compiler.name }} ${{ matrix.compiler.version }})"
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout
@@ -64,27 +69,75 @@ jobs:
         with:
           path: project
 
-      - name: Setup Nim
+      - name: Compiler (nim)
+        if: matrix.compiler.name == 'nim'
         uses: alaviss/setup-nim@0.1.1
         with:
           path: nim
-          version: ${{ matrix.nim }}
+          version: ${{ matrix.compiler.version }}
 
-      - name: Run tests
+      - name: Compiler (nimskull)
+        id: nimskull
+        if: matrix.compiler.name == 'nimskull'
+        uses: alaviss/setup-nimskull@f6e8ade8ac51191024616216e5da0ee968d9da48
+        with:
+          version: ${{ matrix.compiler.version }}
+
+      - if: matrix.compiler.name == 'nimskull'
+        name: Nimble
+        shell: bash
+        run: |
+          cd nimble
+          nim c --define:release --output:nimble src/nimble.nim
+          cp nimble "$NIMSKULL_BIN/nimble"
+          # Add nimble binary folder to PATH too
+          echo "$HOME/.nimble/bin" >> $GITHUB_PATH
+        env:
+          NIMSKULL_BIN: ${{ steps.nimskull.outputs.binPath }}
+
+      - name: Valgrind
+        shell: bash
+        run: |
+          sudo apt-get update
+          sudo apt install --fix-missing valgrind
+
+      - name: Dependencies
+        shell: bash
+        run: |
+          cd project
+          nimble --accept develop
+          nimble --accept install "https://github.com/disruptek/balls"
+        env:
+          NIM: ${{ matrix.compiler.name }}
+
+      - name: Examples
+        shell: bash
+        run: |
+          cd project
+          cd examples
+          balls '***' --path=".." --backend:c --mm:arc || true
+        env:
+          NIM: ${{ matrix.compiler.name }}
+
+      - name: Tests
         shell: bash
         run: |
           cd project
           nimble --accept install
-          balls --path="." --backend:e --backend:js --backend:cpp --backend:c --define:forceRegexAtRuntime
-          # build a dry version
+          balls --path="." --backend:e --backend:js --backend:cpp --backend:c
+          # check things under malloc
+          balls --path="." --backend:cpp --backend:c --define:useMalloc
+          # inspect failure examples
+          nim c --run examples/fails.nim || true
+          # build a dry version of the runner
           nim c --define:ballsDry balls.nim
           # inspect matrix
-          balls --path="." --backend:e --backend:js --backend:cpp --backend:c --define:forceRegexAtRuntime
+          balls --path="." --backend:e --backend:js --backend:cpp --backend:c
           # inspect unit tests
           nim c --run tests/test.nim
 
-      - name: Build docs
-        if: matrix.os == 'ubuntu-latest' && matrix.nim == 'unsupported'
+      - name: Docs
+        if: ${{ matrix.docs }} == 'true'
         shell: bash
         run: |
           cd project
@@ -98,10 +151,10 @@ jobs:
           # Ignore failures for older Nim
           cp docs/{the,}index.html || true
 
-      - name: Publish docs
+      - name: Pages
         if: >
           github.event_name == 'push' && github.ref == 'refs/heads/master' &&
-          matrix.os == 'ubuntu-latest' && matrix.nim == 'unsupported'
+          matrix.os == 'ubuntu-latest' && matrix.docs == 'true'
         uses: crazy-max/ghaction-github-pages@v1
         with:
           build_dir: project/docs
